import 'dart:async';
import 'dart:io';

import 'definitions.dart';

final _header = '''
// This file was generated by Dart-Code-Class-Builder
// and should not be hand-edited!

"use strict";
''';

class TypeScriptGenerator {
  final classes = new List<ClassDefinition>(); 

  Future writeTo(File file) async {
    final output = new StringBuffer(_header);

    classes.forEach((c) => _createClass(output, c));

    await file.parent.create(recursive: true);
    await file.writeAsString(output.toString());
  }

  void _createClass(StringBuffer output, ClassDefinition classDefinition) {
    output.writeln(_formatDoc(classDefinition.doc));
    output.writeln('export class ${classDefinition.name} {');
    output.writeln('}');
    output.writeln();
  }

  String _formatDoc(String doc) {
    final lines = doc.trim().split('\n').map((l) => l.trim());
    return '/**\r\n' + lines.map((l) => ' * $l').join('\r\n') + '\r\n */';
  }
}
