import 'dart:async';
import 'dart:io';

import 'definitions.dart';

final _header = '''
// This file was generated by Dart-Code-Class-Builder
// and should not be hand-edited!

"use strict";

''';

class TypeScriptGenerator {
  final classes = new List<ClassDefinition>(); 

  Future writeTo(File file) async {
    final output = new StringBuffer(_header);

    classes.forEach((c) => _writeClass(output, c));

    await file.parent.create(recursive: true);
    await file.writeAsString(output.toString());
  }

  void _writeClass(StringBuffer output, ClassDefinition cl) {
    output.writeln(_formatDoc(cl.doc));
    output.writeln('export interface ${cl.name} {');
    cl.properties.forEach((p) => _writeProperty(output, p));
    output.writeln('}');
    output.writeln();
  }

  void _writeProperty(StringBuffer output, PropertyDefinition prop) {
    final indent = _getIndent(1);
    output.writeln(_formatDoc(prop.doc, indent: indent));
    output.writeln('$indent${prop.name}${prop.isOptional ? "?" : ""}: ${prop.type};');
    output.writeln();
  }

  String _formatDoc(String doc, { String indent: ""}) {
    final lines = doc.trim().split('\n').map((l) => l.trim());
    return '$indent/**\r\n' + lines.map((l) => '$indent * $l').join('\r\n') + '\r\n$indent */';
  }

  String _getIndent(num level) => '\t' * level;
}
